default_config:
my: 

# auth_providers:
#   - type: homeassistant
#   - type: trusted_networks
#     trusted_networks:
#       - 10.0.0.0/24
#         - 127.0.0.1
#         - ::1
#     allow_bypass_login: true

# auth_header:
#     username_header: X-authentik-username

homeassistant:
  packages: !include_dir_merge_named packages/
  media_dirs:
    local: media

lovelace:
  mode: yaml
  resources: !include dashboards/lovelace_resources.yaml
  dashboards:
    lovelace-overview: 
      mode: yaml
      filename: dashboards/lovelace-tablet.yaml
      title: Tablet Display
      icon: mdi:tablet
      show_in_sidebar: true
      require_admin: false

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js
    - /local/community/custom-brand-icons/custom-brand-icons.js

browser:
powercalc:
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
alert: !include alert.yaml
light: !include light_groups.yaml
sensor: !include sensor.yaml
# input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
switch: !include switches.yaml
binary_sensor: !include binary_sensor.yaml
template: !include templates.yaml

device_tracker:
  - platform: bluetooth_le_tracker
    track_new_devices: false

###############################  iOS  ###############################
ios: !include ios.yaml

#################################  Notify  ###################################
notify: !include notify.yaml

#################################    ###################################
wirelesstag:
  username: !secret my_email
  password: !secret wirelessTagsPassword

#################################  Amcrest  ###################################
# amcrest:
#   - name: Ethan's Camera Amcrest
#     host: 10.0.0.16
#     port: 80
#     username: !secret amcrest_username
#     password: !secret amcrest_password
#     binary_sensors:
#       - motion_detected
#       - crossline_detected
#       - online
#     sensors:
#       - ptz_preset
#   - name: Living Room Amcrest
#     host: 10.0.0.14
#     port: 80
#     username: !secret amcrest_username
#     password: !secret amcrest_password
#     binary_sensors:
#       - motion_detected
#       - crossline_detected
#       - online
#     sensors:
#       - ptz_preset
#   - name: Doorbell Amcrest
#     host: 10.0.0.23
#     port: 80
#     username: !secret amcrest_username
#     password: !secret amcrest_password
#     binary_sensors:
#       - motion_detected
#       - crossline_detected
#       - online
#   - name: Driveway Amcrest
#     host: 10.0.0.251
#     port: 80
#     username: !secret amcrest_username
#     password: !secret amcrest_password
#     binary_sensors:
#       - motion_detected
#       - crossline_detected
#       - online


#################################  Recorder  ###################################
recorder:
  # purge_keep_days: 10
  # commit_interval: 5
  exclude:
    domains:
      - automation
      - update
    entity_globs:
      - sensor.sun*
      - weather.*
      - sensor.browser_*
      - sensor.*uptime
      - sensor.time*
      - input_text.*
    entities:
      - sensor.date
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sun.sun # Don't record sun data
    event_types:
      - call_service # Don't record service calls

#################################  Logbook  ###################################
logbook:
  exclude:
    domains:
      - automation
      - update
    entity_globs:
      - sensor.sun*
      - weather.*
      - sensor.browser_*
      - sensor.*uptime
      - sensor.time*
      - input_text.*
    entities:
      - sensor.date
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sun.sun # Don't record sun data

#################################  InfluxDB  ###################################
influxdb:
  api_version: 2
  ssl: false
  host: !secret host_ip
  port: 8086
  token: !secret influxdb_token
  organization: !secret influxdb_organization
  bucket: hassio
  max_retries: 3
  default_measurement: state
  tags_attributes:
    - friendly_name
    - hidden
  measurement_attr: unit_of_measurement
  exclude:
    entities:
      - zone.home
    domains:
      - persistent_notification
      - person
      - automation
      - camera

#################################  TraktTV  ###################################
trakt_tv:
  language: en # Prefered language for movie/show title
  timezone: America/Los_Angeles # Prefered timezone
  sensors:
    upcoming:
      show:
        days_to_fetch: 30
        max_medias: 10
      movie:
        days_to_fetch: 45
        max_medias: 5
    recommendation:
      show:
        max_medias: 3
      movie:
        max_medias: 3
