title: Home
icon: mdi:home
button_card_templates: !include_dir_merge_named button-card-templates/
views:
  - title: Main Space
    path: main_space
    icon: mdi:home-circle
    type: custom:horizontal-layout
    cards: !include cards/main_space.yaml
  - title: Outdoor
    path: outdoor
    icon: hue:room-outdoors
    type: custom:horizontal-layout
    cards: !include cards/outdoor.yaml
  - title: Living Room
    path: living_room
    icon: mdi:sofa
    type: custom:horizontal-layout
    cards: !include cards/living-room.yaml
  - title: Entertainment Center
    path: tv_main
    icon: mdi:television
    type: custom:horizontal-layout
    cards: !include cards/entertainment_center.yaml
  - title: kitchen
    path: kitchen
    icon: mdi:countertop
    type: custom:horizontal-layout
    cards: !include cards/kitchen.yaml
  - title: Master
    path: master
    icon: mdi:bed-king
    type: custom:horizontal-layout
    cards: !include cards/master.yaml
  - title: Family Room
    path: family
    icon: hue:room-lounge
    panel: false
    type: custom:horizontal-layout
    cards: !include cards/family-room.yaml
  - title: Ethan's Room
    path: ethan
    icon: hue:room-nursery
    type: custom:horizontal-layout
    cards: !include cards/ethans-room.yaml
  - title: Office
    path: office
    icon: mdi:desk
    type: custom:horizontal-layout
    cards: !include cards/office.yaml
  # - title: power
  #   path: power
  #   icon: mdi:flash
  #   type: custom:horizontal-layout
  #   cards: !include cards/power.yaml
  - title: Growing
    path: Growing
    icon: mdi:greenhouse
    type: custom:horizontal-layout
    cards: !include cards/greenhouse.yaml
  # - title: Temperatures
  #   path: temps
  #   icon: mdi:thermometer
  #   type: custom:grid-layout
  #   layout:
  #     grid-template-columns: 100%
  #     grid-template-rows: 250px
  #   cards: !include cards/temperatures.yaml

  - title: Media
    path: meida
    icon: mdi:music
    type: custom:horizontal-layout
    cards: !include cards/media.yaml

  - title: Attic
    path: attic
    icon: hue:room-attic
    type: custom:horizontal-layout
    cards: !include cards/attic.yaml

  - title: Crawl Space
    path: crawl
    icon: mdi:home-floor-negative-1
    type: custom:horizontal-layout
    cards: !include cards/crawl_space.yaml
