- platform: template
  switches:
    garage_door_main:
      friendly_name: "Main Garage Door Switch"
      value_template: "{{ is_state('cover.garage_door', 'open') }}"
      turn_on:
        service: cover.open_cover
        data:
          entity_id: cover.garage_door
      turn_off:
        service: cover.close_cover
        data:
          entity_id: cover.garage_door
      icon_template: >-
        {% if is_state('cover.main_garage_door', 'open') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}
- platform: group
  name: All Grow Lights [Group]
  entities:
    - switch.basement_couch_grow_light
    - switch.family_room_tv_grow_light
    - switch.master_bedroom_grow_light
    - switch.basement_bathroom_grow_light
- platform: group
  name: Christmas Lights [Group]
  entities:
    - switch.yard_christmas_lights
    - switch.cabinet_switch
    - switch.left_greenhouse_plug