button_card_templates: !include_dir_merge_named dashboards/button-card-templates/
show_in_sidebar: true

views: 
  - !include dashboards/views/home.yaml
  # - !include dashboards/views/tablet-home.yaml
  - !include dashboards/views/cameras.yaml
  # - title: Switches
  #   icon: mdi:light-switch
  #   path: Switches
  #   visible: true
  #   cards: !include cards/wall_switches.yaml
  - !include dashboards/views/requests.yaml
  - !include dashboards/views/living_room_remote.yaml
  - !include dashboards/views/family_room_remote.yaml
  - !include dashboards/views/scheduling.yaml
  - !include dashboards/views/fun.yaml
  - !include dashboards/views/misc.yaml
  # - !include dashboards/old/dash-home.yaml

  # - !include dashboards/views/rooms.yaml
  # - title: Kitchen
  #   path: kitchen
  #   visible: false
  #   cards: !include dashboards/views/kitchen.yaml
  # - title: Living Room
  #   path: living
  #   visible: false
  #   cards: !include dashboards/views/living_room/living-room.yaml
  # - title: Master Bedroom
  #   path: master
  #   visible: false
  #   type: custom:vertical-layout
  #   cards: !include dashboards/views/master.yaml
  # - title: Ethan
  #   path: ethan
  #   visible: false
  #   cards: !include dashboards/views/ethans-room.yaml
  # - title: Family Room
  #   path: family
  #   visible: false
  #   cards: !include dashboards/views/family-room.yaml
  # - title: Office
  #   path: office
  #   visible: false
  #   cards: !include dashboards/views/office.yaml
  # - title: Outdoors
  #   path: outdoors
  #   visible: false
  #   cards: !include dashboards/views/outdoor.yaml
  # - title: Holiday
  #   path: holiday
  #   visible: false
  #   cards: !include dashboards/views/holiday.yaml
