#!/usr/bin/env python3
"""Port the GUI (storage) room pages into the YAML dashboard's room pop-ups.

Reads the GUI dashboard from .storage and writes each room page to
dashboards/sections/rooms/<room>/, one file per GUI section, converting cards to the
shared templates described in dashboards/ARCHITECTURE.md:

  heading                      -> Bubble separator (heading badges become sub-buttons)
  page badges, mushroom chips  -> bubble_chips
  simple Bubble light/switch   -> bubble_light / _color / _temp / _effect, bubble_switch
  anything else                -> copied unchanged (GUI-only layout keys removed)

Run inside the Home Assistant container (it has PyYAML):

    docker exec Home-Assistant-Core python3 /config/dashboards/tools/port_gui_rooms.py [room ...]
    docker exec Home-Assistant-Core python3 /config/dashboards/tools/port_gui_rooms.py --dry-run

Files this script writes carry MARKER and are replaced on every run. Other files in a
room directory (e.g. 90-air-quality.yaml) are left alone. Afterwards touch
dashboards/lovelace-main.yaml so Home Assistant reloads the dashboard.
"""
import argparse
import json
import re
import sys
from pathlib import Path

import yaml

CONFIG = Path(__file__).resolve().parents[2]
GUI_DASHBOARD = CONFIG / ".storage" / "lovelace.lovelace_mushroom"
ENTITY_REGISTRY = CONFIG / ".storage" / "core.entity_registry"
ROOMS_DIR = CONFIG / "dashboards" / "sections" / "rooms"
MARKER = "Generated by dashboards/tools/port_gui_rooms.py"

# GUI view path -> (sections/rooms/<dir>, the room's pop-up hash)
ROOMS = {
    "kitchen": ("kitchen", "#kitchen"),
    "living-room": ("living-room", "#living-room"),
    "master_bedroom": ("master-bedroom", "#master"),
    "family-room": ("family-room", "#family"),
    "office": ("office", "#office"),
    "ethan-bedroom": ("ethan", "#ethan"),
    "outdoors": ("outdoors", "#outdoors"),
}

COLOR_MODES = {"hs", "rgb", "rgbw", "rgbww", "xy"}
TOGGLE_ICONS = {None, "", "mdi:power", "mdi:lightbulb"}
STACKS = {"vertical-stack", "horizontal-stack", "grid", "custom:stack-in-card"}
GUI_ONLY_KEYS = {"grid_options", "view_layout"}
STATE_BACKGROUND_DOMAINS = {"binary_sensor", "input_boolean", "switch", "light", "fan", "cover", "lock"}
ENTITY_RE = re.compile(
    r"\b(?:alarm_control_panel|automation|binary_sensor|camera|climate|cover|fan|input_boolean|"
    r"input_datetime|input_number|light|lock|media_player|number|remote|select|sensor|switch|"
    r"water_heater|weather)\.[a-z0-9_]+\b"
)


class Porter:
    def __init__(self, registry):
        self.registry = registry
        self.warnings = []
        self.converted = 0

    def warn(self, message):
        self.warnings.append(message)

    # ---- lights and switches -------------------------------------------------
    def light_template(self, entity_id):
        caps = (self.registry.get(entity_id) or {}).get("capabilities") or {}
        modes = set(caps.get("supported_color_modes") or [])
        if modes & COLOR_MODES:
            return "bubble_light_color"
        if "color_temp" in modes:
            return "bubble_light_temp"
        if modes == {"onoff"}:
            return "bubble_switch"
        if entity_id not in self.registry:
            self.warn(f"{entity_id}: not in the entity registry, used bubble_light")
        return "bubble_light"

    def effect_selects(self, entity_id):
        object_id = entity_id.split(".", 1)[1]
        palette = f"select.{object_id}_color_palette"
        preset = f"select.{object_id}_preset"
        if palette in self.registry and preset in self.registry:
            return palette, preset
        return None, None

    @staticmethod
    def split_sub_buttons(card):
        sub = card.get("sub_button") or []
        if isinstance(sub, list):
            return sub, []
        return sub.get("main") or [], sub.get("bottom") or []

    @staticmethod
    def toggle_only(main, entity_id):
        if len(main) > 1:
            return False
        for button in main:
            action = (button.get("tap_action") or {}).get("action")
            if button.get("entity") not in (None, entity_id):
                return False
            if button.get("icon") not in TOGGLE_ICONS or action not in (None, "toggle"):
                return False
        return True

    def bubble_control(self, card):
        entity_id = card.get("entity")
        if card.get("card_type") != "button" or not entity_id:
            return None
        domain = entity_id.split(".", 1)[0]
        if domain not in ("light", "switch", "fan", "input_boolean"):
            return None
        button_type = card.get("button_type") or ("slider" if domain == "light" else "switch")
        if button_type not in ("slider", "switch") or card.get("modules") or card.get("styles"):
            return None
        main, bottom = self.split_sub_buttons(card)
        if not self.toggle_only(main, entity_id):
            return None

        extra = []
        if domain == "light" and any(b.get("sub_button_type") == "select" for b in bottom):
            palette, preset = self.effect_selects(entity_id)
            if not palette:
                return None
            template = "bubble_light_effect"
            extra = [{"palette": palette}, {"preset": preset}]
            dropped = [b.get("name") or b.get("entity") for b in bottom if b.get("sub_button_type") != "select"]
            if dropped:
                self.warn(f"{entity_id}: bubble_light_effect has no room for {', '.join(map(str, dropped))}")
        elif bottom:
            return None
        elif domain == "light":
            template = self.light_template(entity_id)
        else:
            template = "bubble_switch"

        variables = [{"entity": entity_id}]
        if card.get("name"):
            variables.append({"name": card["name"]})
        if card.get("icon"):
            variables.append({"icon": card["icon"]})
        self.converted += 1
        return {"type": "custom:decluttering-card", "template": template, "variables": variables + extra}

    # ---- headings, badges and chips -----------------------------------------
    def separator(self, heading):
        card = {"type": "custom:bubble-card", "card_type": "separator", "name": heading.get("heading", "")}
        if heading.get("icon"):
            card["icon"] = heading["icon"]
        buttons = []
        for badge in heading.get("badges") or []:
            if not badge.get("entity"):
                continue
            button = {"entity": badge["entity"], "show_state": badge.get("show_state", True), "show_background": False}
            if badge.get("icon"):
                button["icon"] = badge["icon"]
            if badge.get("show_icon") is False:
                button["show_icon"] = False
            buttons.append(button)
        if buttons:
            card["sub_button"] = buttons
        self.converted += 1
        return card

    def chip(self, source, from_badge=False):
        kind = source.get("type", "entity")
        if kind == "conditional":
            chip = self.chip(source.get("chip") or {})
            if chip:
                chip["visibility"] = source.get("conditions") or []
            return chip
        entity_id = source.get("entity")
        if not entity_id:
            self.warn(f"dropped a {kind} chip without an entity")
            return None

        chip = {"entity": entity_id}
        name, icon = source.get("name"), source.get("icon")
        if isinstance(name, str) and name:
            chip["name"] = name
        if isinstance(icon, str) and icon and "{" not in icon:
            chip["icon"] = icon

        if from_badge:
            show_name, show_state = source.get("show_name", True), source.get("show_state", True)
        elif source.get("content_info") == "name":
            show_name, show_state = True, False
        elif source.get("content_info") == "none":
            show_name, show_state = False, False
        elif kind == "template":
            # Templated text can't be ported; the entity's name and state say the same thing.
            show_name, show_state = True, True
        else:
            show_name, show_state = False, True
        if show_name:
            chip["show_name"] = True
        chip["show_state"] = show_state
        if entity_id.split(".", 1)[0] in STATE_BACKGROUND_DOMAINS:
            chip["state_background"] = True
        chip["fill_width"] = False
        for key in ("tap_action", "hold_action", "double_tap_action"):
            if source.get(key):
                chip[key] = source[key]
        return chip

    def chips_card(self, chips):
        chips = [c for c in chips if c]
        self.converted += 1
        return {"type": "custom:decluttering-card", "template": "bubble_chips", "variables": [{"chips": chips}]}

    # ---- cards ----------------------------------------------------------------
    def convert(self, card):
        card = {k: v for k, v in card.items() if k not in GUI_ONLY_KEYS}
        kind = card.get("type")
        if kind == "heading":
            return self.separator(card)
        if kind == "custom:mushroom-chips-card":
            return self.chips_card([self.chip(c) for c in card.get("chips") or []])
        if kind == "custom:bubble-card":
            sub = card.get("sub_button")
            if isinstance(sub, dict) and isinstance(sub.get("bottom"), list):
                # Empty sub-button groups left behind by the GUI editor render as blank rows.
                sub["bottom"] = [b for b in sub["bottom"] if not ("group" in b and not b["group"])]
            return self.bubble_control(card) or card
        if kind in STACKS and isinstance(card.get("cards"), list):
            card["cards"] = [self.convert(c) for c in card["cards"]]
        return card


# ---- output -------------------------------------------------------------------
class Dumper(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True

    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow, False)


def _str(dumper, value):
    style = "|" if "\n" in value else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", value, style=style)


Dumper.add_representer(str, _str)


def to_yaml(data):
    return yaml.dump(data, Dumper=Dumper, sort_keys=False, allow_unicode=True, width=120, indent=2)


def slugify(text):
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-") or "section"


def section_title(cards, index):
    for card in cards:
        if card.get("type") == "heading" and card.get("heading"):
            return card["heading"]
        if card.get("card_type") == "separator" and card.get("name"):
            return card["name"]
    for card in cards:
        for key in ("name", "title"):
            if isinstance(card.get(key), str) and card[key]:
                return card[key]
        camera = (card.get("cameras") or [{}])[0].get("camera_entity")
        if camera:
            return camera.split(".", 1)[1]
    return "controls" if index == 0 else f"section-{index + 1}"


def strip_actions(data):
    """Drop service/action names so they aren't mistaken for entity ids."""
    if isinstance(data, dict):
        return {k: strip_actions(v) for k, v in data.items() if k not in ("service", "perform_action", "action")}
    if isinstance(data, list):
        return [strip_actions(v) for v in data]
    return data


def links_to(card, popup_hash):
    return f'"navigation_path": "{popup_hash}"' in json.dumps(card)


def port_room(porter, view, room_dir, popup_hash, dry_run):
    title = view.get("title") or view.get("path")
    header = (
        f"# {MARKER} from the GUI \"{title}\" page.\n"
        "# Edit the page in the GUI and re-run the script; changes made here are overwritten.\n"
    )
    files = {}
    if view.get("badges"):
        chips = [porter.chip(b, from_badge=True) for b in view["badges"] if b.get("type", "entity") == "entity"]
        files["00-badges.yaml"] = porter.chips_card(chips)

    for index, section in enumerate(view.get("sections") or []):
        cards = section.get("cards") or []
        kept = [c for c in cards if not links_to(c, popup_hash)]
        if len(kept) != len(cards):
            porter.warn(f"{title}: skipped {len(cards) - len(kept)} card(s) that open this pop-up")
        if not kept:
            continue
        converted = [porter.convert(c) for c in kept]
        doc = converted[0] if len(converted) == 1 else {"type": "vertical-stack", "cards": converted}
        files[f"{(index + 1) * 10:02d}-{slugify(section_title(kept, index))}.yaml"] = doc

    out_dir = ROOMS_DIR / room_dir
    if not dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)
        for old in out_dir.glob("*.yaml"):
            if MARKER in old.read_text()[:300]:
                old.unlink()
    for name, doc in files.items():
        if not dry_run:
            (out_dir / name).write_text(header + to_yaml(doc))
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("rooms", nargs="*", help=f"GUI view paths to port (default: all of {', '.join(ROOMS)})")
    parser.add_argument("--dry-run", action="store_true", help="report what would be written without writing")
    args = parser.parse_args()

    views = {v.get("path"): v for v in json.loads(GUI_DASHBOARD.read_text())["data"]["config"]["views"]}
    entities = json.loads(ENTITY_REGISTRY.read_text())["data"]["entities"]
    registry = {e["entity_id"]: e for e in entities}

    status = 0
    for path in args.rooms or list(ROOMS):
        if path not in ROOMS or path not in views:
            print(f"!! {path}: unknown room (known: {', '.join(ROOMS)})")
            status = 1
            continue
        room_dir, popup_hash = ROOMS[path]
        porter = Porter(registry)
        files = port_room(porter, views[path], room_dir, popup_hash, args.dry_run)

        referenced = set(ENTITY_RE.findall(json.dumps(strip_actions(list(files.values())))))
        missing = sorted(e for e in referenced if e not in registry)
        print(f"== {path} -> sections/rooms/{room_dir}/ ({porter.converted} cards converted)")
        for name in files:
            print(f"   {name}")
        for message in porter.warnings:
            print(f"   note: {message}")
        if missing:
            print(f"   not in the entity registry: {', '.join(missing)}")
    return status


if __name__ == "__main__":
    sys.exit(main())
