inovelli_parameter:
  name: Inovelli Parameter
  options:
    - LED Color
    - LED Intensity
    - LED When On
    - LED When Off
    - Fan Speed Control
    - Smart Bulb Mode
    - Dimming Speed
    - Ramp Rate
    - Default Level
    - Power On State
    - Scene Control
  initial: LED Color
  icon: mdi:tune
cube_room:
  name: Magic Cube Room
  options:
    - Master
    - Ethan
    - Office
    - Family
    - Main
  icon: mdi:cube-outline
cube_scene_preset:
  name: Magic Cube Scene
  options:
    - Bright
    - Relax
    - Movie
    - Night
    - Campfire
    - Deep Sea
    - Aurora
    - Disco
    - Enchanted
    - Sunset
  icon: mdi:palette