inovelli_parameter_value:
  name: Parameter Value
  min: 0
  max: 255
  step: 1
  initial: 0
  icon: mdi:numeric
cube_bulb_index:
  name: Magic Cube Bulb Index
  min: 0
  max: 20
  step: 1
  mode: box
  icon: mdi:lightbulb-group

# ethan_daily_stars_earned:
#   name: "Stars Earned Today"
#   initial: 0
#   min: 0
#   max: 20
#   step: 1
#   icon: mdi:star
# ethan_weekly_stars:
#   name: "Weekly Stars"
#   initial: 0
#   min: 0
#   max: 140
#   step: 1
#   icon: mdi:star-circle