blueprint:
  source_url: https://community.home-assistant.io/t/ring-keypad-v2-sounds-script-zwavejs/680399
  name: Ring Keypad v2 Sounds, ZwaveJS
  description: >
    # Ring Keypad v2 Sounds
    
    Trigger built-in sounds for the Ring Keypad v2 using ZwaveJS.
    
    ## 📑 Changelog

    * **2024-3-24**: 🔢 Allow multiple keypads in the same blueprint.
    * **2024-1-27**: 🎉 First Version
    
    
    
    Required = *
    
    
    
    **If you like this blueprint or have suggestions comment back on the original post.** [Click Here]()
  domain: script
  input:
    keypad:
      name: Ring Keypad Device *
      description: The device entry for the Ring keypad
      selector:
        device:
          manufacturer: Ring
          integration: zwave_js
          multiple: true
    sound_selection:
      name: Keypad Sound *
      description: > 
        Choose the sound to play. 
        
        
        
        WARNING: The **Alarm** options will not stop until the keypad mode is changed.
      default: "96"
      selector:
        select:
          mode: list
          options:
            - label: "🚨 *Alarm* CO2 (Inludes flashing lights)"
              value: "15"
            - label: "🚨 *Alarm* Fire (Inludes flashing lights)"
              value: "14"
            - label: "🚨 *Alarm* Medical (Silent, flashing lights only)"
              value: "19"
            - label: "🚨 *Alarm* Police (Inludes flashing lights)"
              value: "13"
            - label: 🔔 Ding Ding
              value: "96"
            - label: 🔊 Echoing Bing Bong
              value: "99"
            - label: 💢 Error Soft Dual Tone
              value: "9"
            - label: 🎸 Guitar Riff
              value: "97"
            - label: 🚪 Ring Doorbell Chime
              value: "100"
            - label: 💨 Wind Chimes
              value: "98"
    sound_volume:
      name: Keypad Volume *
      description: Choose the volume to play the sound.
      default: 50
      selector:
        number:
          min: 10
          max: 100
          step: 10
          unit_of_measurement: '%'
          mode: slider

mode: single

sequence:
  - service: zwave_js.set_value
    target:
      device_id: !input keypad
    data:
      command_class: 135
      endpoint: 0
      property: !input sound_selection
      property_key: 9
      value: !input sound_volume