blueprint:
  name: Push Button Relay - Contactor
  description: "# PUSH BUTTON - RELAY - CONTACTOR\nVersion: 1.2\n\nThe most common
    automation used for a relay or contactor with a push button (press button). It
    has a \"Normally Open\" (NO) and a \"Normally Closed\" (NC) contacts controlled
    by a push button (press button) entity. You can add as many \"Normally Open\"
    and \"Normally Closed\" entities as you like.\n\nUse case\n - You can create a
    \"Push Button\" (press button) entity or have a physical push button and control
    a bunch of light switches.\n - Have a push button near your bed to turn ON and
    OFF your lights or have a push button to turn ON and OFF all your garden lights
    switches.\n\n\nFor community support see this forum post: [Click Here](https://community.home-assistant.io/t/push-button-relay-contactor/481543)\n\nGitHub:
    [Click Here](https://gist.github.com/Blackshome/fd16903e90c2aa58c75e92d2cafc6115)\n\nThe
    Automation Process:\n - When you press the button it will turn ON the Normal Open
    contact and turn OFF the Normally Closed contact.\n - When you press the button
    again it will turn OFF the Normal Open contact and turn ON the Normally Closed
    contact.\n \n **If you like my blueprints, and would like to show your support
    or just say thank you?** [Click Here](https://community.home-assistant.io/u/blacky/summary)
    \U0001F642\n"
  domain: automation
  input:
    switch:
      name: Push Button Switch
      description: The push button (press button) that controls the relay.
      selector:
        entity: {}
    normally_open:
      name: Normally Open
      description: The normally open contact. Select what will be turned ON when the
        button is pressed.
      selector:
        entity:
          multiple: true
      default: []
    normally_closed:
      name: Normally Closed
      description: The normally closed contact. Select what will be turned OFF when
        the button is pressed.
      selector:
        entity:
          multiple: true
      default: []
  source_url: https://gist.github.com/Blackshome/fd16903e90c2aa58c75e92d2cafc6115
variables:
  switch: !input switch
  normally_open: !input normally_open
  normally_closed: !input normally_closed
trigger:
- platform: state
  entity_id: !input switch
  to: 'on'
action:
- alias: Turn ON the normally open
  service: homeassistant.turn_on
  entity_id: !input normally_open
- alias: Turn OFF the normally closed
  service: homeassistant.turn_off
  entity_id: !input normally_closed
- alias: Wait until switch is OFF
  wait_for_trigger:
    platform: state
    entity_id: !input switch
    to: 'on'
- alias: Turn OFF the normally open
  service: homeassistant.turn_off
  entity_id: !input normally_open
- alias: Turn ON the normally closed
  service: homeassistant.turn_on
  entity_id: !input normally_closed
